### ISSUE TITLE
爬取用户主页视频数据，api：douyin_profile_videos

### ISSUE THREAD

**Issue by panmili** [TikHubIO/TikHub_API_PyPi#4]
昨天还是没有问题的，今天就不行了，返回如下信息：{"status":"failed","platform":"douyin","endpoint":null,"message":"获取视频数据失败/Failed to get video data","has_more":null,"cursor":null,"next_url":null,"count":null,"total_time":null,"aweme_list":null}

**Comment by Evil0ctal** [comment]
好的，会尽快解决。
