### ISSUE TITLE
请教一下鉴权机制，test账户是否有使用次数或者频率的限制？如有如何申请高等级权限

### ISSUE THREAD

**Issue by kelei1988** [TikHubIO/TikHub_API_PyPi#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by callmeiks** [comment]
暂时没有设置。但是一月底左右我们会开始设置限制，到时候会进行更新。由于我们现在是免费的，所以没有限制。但很快我们会进行收费，您可以选择不同的plan来决定您需要的使用次数。
