### ISSUE TITLE
API.get_tiktok_profile_videos() Doesn`t work as of now

### ISSUE THREAD

**Issue by TFEI-Terminal** [TikHubIO/TikHub_API_PyPi#8]
**Describe the bug**
API.get_tiktok_profile_videos() Doesn`t work as of the time when this issue is submitted.

**To Reproduce**
tiktok_url = 'https://www.tiktok.com/@evil0ctal/video/7156033831819037994'
aweme_list = await api.get_tiktok_profile_videos(tiktok_url, 20)

**Additional context**
TypeError: 'NoneType' object is not iterable

**Comment by TFEI-Terminal** [comment]
seems its ok now.

**Comment by TFEI-Terminal** [comment]
It seems the api stops working after a few calls,

**Comment by Evil0ctal** [comment]
Will try to make it more stable!
